# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='persons.Employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[(b'BUY', b'buy'), (b'SELL', b'sell')], max_length=50),
        ),
    ]
