# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20171029_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell')], max_length=50),
        ),
    ]
